spring:
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
  datasource:
    name: sa
    password: sa
    url: jdbc:sqlite:database/sqlite.db
    driver-class-name: org.sqlite.JDBC
  flyway:
    locations: classpath:db/migration
